apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Chart.Name }}
data:
  NODE_ENV: {{ .Values.global.environment | quote }}
  APP_TENANT: {{ .Values.global.tenant | quote }}
  PORT: "8080"
