'use client';

import { useState, useEffect } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { AlertTriangle, Loader2, Navigation, Hexagon, Eye, EyeOff } from 'lucide-react';
import { BrandSplash } from '@/components/brand-splash';

function getValidatedCallbackUrl(url: string | null): string | null {
  if (!url) return null;
  try {
    const parsed = new URL(url, window.location.origin);
    return parsed.origin === window.location.origin ? parsed.pathname + parsed.search + parsed.hash : null;
  } catch {
    return null;
  }
}

import { api } from '@/services/api';
import { useAuthStore } from '@/store/auth';
import { getDashboardRouteForRole } from '@/utils/role-router';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useMfa } from '@/hooks/use-mfa';

const loginSchema = z.object({
  email: z.string().email('Please enter a valid enterprise email address.'),
  password: z.string().min(8, 'Password must be at least 8 characters.'),
});

type LoginFormValues = z.infer<typeof loginSchema>;

import { Suspense } from 'react';

export default function LoginPage() {
  return (
    <Suspense fallback={<div className="flex justify-center p-8"><Loader2 className="h-8 w-8 animate-spin" /></div>}>
      <LoginContent />
    </Suspense>
  );
}

function LoginContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const setAuth = useAuthStore((state) => state.setAuth);
  const [error, setError] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [showPassword, setShowPassword] = useState(false);
  const [capsLockOn, setCapsLockOn] = useState(false);
  const [isMounted, setIsMounted] = useState(false);
  const { isMfaRequired, verifyMfa, mfaToken, setMfaRequired } = useMfa();

  const { register, handleSubmit, formState: { errors } } = useForm<LoginFormValues>({
    resolver: zodResolver(loginSchema) as any,
  });

  useEffect(() => {
    setIsMounted(true);
    const handleKeyDown = (e: KeyboardEvent) => {
      if (typeof e.getModifierState === 'function' && e.getModifierState('CapsLock')) {
        setCapsLockOn(true);
      } else {
        setCapsLockOn(false);
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, []);

  const onSubmit = async (data: LoginFormValues) => {
    setIsLoading(true);
    setError(null);
    try {
      const response = await api.post('/auth/login', data);
      
      if (response.data.requires_mfa) {
        setMfaRequired(true);
        return;
      }
      
      const user = response.data.user;
      setAuth(user, response.data.access_token);
      
      // Ensure auth state is persisted before navigation
      await new Promise(resolve => setTimeout(resolve, 500));
      // Automatic RBAC Redirection (Phase 3)
      const callback = getValidatedCallbackUrl(searchParams.get('callbackUrl'));
      const targetRoute = callback || getDashboardRouteForRole(user.role, user.onboardingCompleted);
      router.replace(targetRoute);
      
    } catch (err: any) {
      setError(err.normalizedMessage || 'Invalid credentials or tenant configuration.');
    } finally {
      setIsLoading(false);
    }
  };

  const handleMfaSubmit = async (code: string) => {
    setIsLoading(true);
    try {
      const response = await verifyMfa(code);
      const user = response.data.user;
      setAuth(user, response.data.access_token);
      
      const targetRoute = getDashboardRouteForRole(user.role, user.onboardingCompleted);
      router.push(targetRoute);
    } catch (err: any) {
      setError('Invalid MFA verification code.');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <>
      <BrandSplash />
      <div className="flex flex-col min-h-[500px]">
        <div className="flex justify-center mb-8">
        <img src="/brand/parilink-logo-full.png" alt="PariLink" className="h-12 w-auto object-contain" />
      </div>

      <h2 className="text-3xl font-medium tracking-tight text-white">
        Log in to your account
      </h2>
      <p className="mt-2 text-sm text-white/60 font-mono tracking-widest uppercase">
        Securely access your enterprise workspace.
      </p>

      <div className="mt-8 relative">
        {isMfaRequired ? (
          <div className="space-y-6 animate-in slide-in-from-right-4 duration-300">
            <p className="text-sm text-slate-600 dark:text-slate-400">
              Please enter the 6-digit verification code generated by your Authenticator app.
            </p>
            {error && (
              <div className="p-3 text-sm text-red-700 bg-red-50 border border-red-200 rounded-lg animate-shake flex items-center gap-2 dark:bg-red-950/50 dark:border-red-900/50 dark:text-red-400">
                <AlertTriangle className="h-4 w-4" />
                {error}
              </div>
            )}
            <div className="space-y-2">
              <Label htmlFor="mfa" className="font-semibold">Verification Code</Label>
              <Input
                id="mfa"
                type="text"
                placeholder="000000"
                maxLength={6}
                className="text-2xl tracking-[0.5em] text-center font-mono h-14"
                onChange={(e) => {
                  if (e.target.value.length === 6) {
                    handleMfaSubmit(e.target.value);
                  }
                }}
              />
            </div>
            <Button className="w-full h-11" variant="outline" disabled={isLoading} onClick={() => setMfaRequired(false)}>
              Back to Login
            </Button>
          </div>
        ) : (
          <form onSubmit={handleSubmit(onSubmit)} action="javascript:void(0);" className="space-y-5">
          {error && (
            <div className="p-3 text-sm text-red-700 bg-red-50 border border-red-200 rounded-lg animate-shake flex items-center gap-2 dark:bg-red-950/50 dark:border-red-900/50 dark:text-red-400">
              <AlertTriangle className="h-4 w-4" />
              {error}
            </div>
          )}

          <div className="space-y-2">
            <Label htmlFor="email" className="text-xs font-mono uppercase tracking-widest text-white/70">Work Email</Label>
            <Input
              id="email"
              type="email"
              autoComplete="email"
              placeholder="name@company.com"
              {...register('email')}
              className={`h-11 bg-black/50 border-white/10 text-white rounded-none focus-visible:ring-[#FF4500] focus-visible:border-[#FF4500] transition-colors font-mono ${errors.email ? 'border-red-500' : ''}`}
            />
            {errors.email && <p className="text-xs text-[#FF4500] font-mono animate-in slide-in-from-top-1">{errors.email.message}</p>}
          </div>

          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <Label htmlFor="password" className="text-xs font-mono uppercase tracking-widest text-white/70">Password</Label>
              <a href="/forgot-password" className="text-[10px] font-mono uppercase tracking-widest text-white/40 hover:text-white transition-colors">
                Forgot password?
              </a>
            </div>
            <div className="relative">
              <Input
                id="password"
                type={showPassword ? "text" : "password"}
                autoComplete="current-password"
                {...register('password')}
                className={`h-11 pr-10 bg-black/50 border-white/10 text-white rounded-none focus-visible:ring-[#FF4500] focus-visible:border-[#FF4500] transition-colors font-mono tracking-widest ${errors.password ? 'border-red-500' : ''}`}
              />
              <button
                type="button"
                onClick={() => setShowPassword(!showPassword)}
                className="absolute right-3 top-3 text-white/40 hover:text-white transition-colors"
                tabIndex={-1}
              >
                {showPassword ? <EyeOff className="h-5 w-5" /> : <Eye className="h-5 w-5" />}
              </button>
            </div>
            {capsLockOn && <p className="text-[10px] text-yellow-500 font-mono flex items-center gap-1 mt-1 uppercase"><AlertTriangle className="h-3 w-3" /> Caps Lock is on</p>}
            {errors.password && <p className="text-xs text-[#FF4500] font-mono animate-in slide-in-from-top-1">{errors.password.message}</p>}
          </div>

          <div className="flex items-center space-x-2 pt-2 pb-4">
            <input type="checkbox" id="remember" className="rounded-none border-white/20 bg-black/50 text-[#FF4500] focus:ring-[#FF4500] h-4 w-4 transition-all" />
            <Label htmlFor="remember" className="text-[10px] font-mono uppercase tracking-widest text-white/60 leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
              Remember this device
            </Label>
          </div>

          <Button type="submit" className="w-full h-12 rounded-none text-sm font-mono uppercase tracking-widest transition-all duration-200 bg-[#FF4500] text-white hover:bg-[#FF4500]/90 border border-[#FF4500] hover:shadow-[0_0_15px_rgba(255,69,0,0.5)]" disabled={isLoading}>
            {isLoading ? (
              <span className="flex items-center gap-2">
                <Loader2 className="h-4 w-4 animate-spin" />
                Authenticating...
              </span>
            ) : (
              'Sign in to PariLink'
            )}
          </Button>
        </form>
        )}

        {!isMfaRequired && (
          <div className="mt-8">
            <div className="relative">
              <div className="absolute inset-0 flex items-center">
                <div className="w-full border-t border-white/10" />
              </div>
              <div className="relative flex justify-center text-[10px]">
                <span className="bg-[#0A0A0A] px-3 text-white/40 uppercase font-mono tracking-widest">Enterprise SSO</span>
              </div>
            </div>

            <div className="mt-6">
              <Button
                type="button"
                variant="outline"
                className="w-full h-12 rounded-none font-mono uppercase tracking-widest text-xs bg-black/50 border-white/10 hover:bg-white/10 text-white transition-colors"
                onClick={() => window.location.href = `${process.env.NEXT_PUBLIC_API_URL}/auth/saml/login`}
              >
                Continue with SAML SSO
              </Button>
            </div>
          </div>
        )}
      </div>

      <div className="mt-auto pt-10 text-center">
        <p className="text-[10px] text-white/40 font-mono tracking-widest uppercase">
          © {new Date().getFullYear()} PariLink Enterprise. All rights reserved. V2.4.1
        </p>
        <div className="flex justify-center gap-6 mt-3 text-[10px] text-white/40 font-mono tracking-widest uppercase">
          <a href="/legal/privacy" className="hover:text-white transition-colors">Privacy Policy</a>
          <a href="/legal/terms" className="hover:text-white transition-colors">Terms of Service</a>
        </div>
      </div>
    </div>
    </>
  );
}
