'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { Hexagon, Loader2, Eye, EyeOff, AlertTriangle } from 'lucide-react';
import { api } from '@/services/api';
import { useAuthStore } from '@/store/auth';
import { getDashboardRouteForRole } from '@/utils/role-router';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useMfa } from '@/hooks/use-mfa';

const loginSchema = z.object({
  email: z.string().email('Please enter a valid enterprise email address.'),
  password: z.string().min(8, 'Password must be at least 8 characters.'),
});

type LoginFormValues = z.infer<typeof loginSchema>;

export default function LoginPage() {
  const router = useRouter();
  const setAuth = useAuthStore((state) => state.setAuth);
  const [error, setError] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [showPassword, setShowPassword] = useState(false);
  const [capsLockOn, setCapsLockOn] = useState(false);
  const { isMfaRequired, verifyMfa, mfaToken, setMfaRequired } = useMfa();

  const { register, handleSubmit, formState: { errors } } = useForm<LoginFormValues>({
    resolver: zodResolver(loginSchema) as any,
  });

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.getModifierState('CapsLock')) setCapsLockOn(true);
      else setCapsLockOn(false);
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, []);

  const onSubmit = async (data: LoginFormValues) => {
    setIsLoading(true);
    setError(null);
    try {
      const response = await api.post('/auth/login', data);
      
      if (response.data.requires_mfa) {
        setMfaRequired(true);
        return;
      }
      
      const user = response.data.user;
      setAuth(user, response.data.access_token);
      
      // Automatic RBAC Redirection (Phase 3)
      const targetRoute = getDashboardRouteForRole(user.role, user.onboardingCompleted);
      router.push(targetRoute);
      
    } catch (err: any) {
      setError(err.normalizedMessage || 'Invalid credentials or tenant configuration.');
    } finally {
      setIsLoading(false);
    }
  };

  const handleMfaSubmit = async (code: string) => {
    setIsLoading(true);
    try {
      const response = await verifyMfa(code);
      const user = response.data.user;
      setAuth(user, response.data.access_token);
      
      const targetRoute = getDashboardRouteForRole(user.role, user.onboardingCompleted);
      router.push(targetRoute);
    } catch (err: any) {
      setError('Invalid MFA verification code.');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex flex-col min-h-[500px]">
      <div className="flex items-center gap-3 mb-8">
        <div className="bg-slate-900 dark:bg-white p-2.5 rounded-xl shadow-lg border border-slate-800 dark:border-slate-200 shadow-[inset_0_1px_0_rgba(255,255,255,0.2)]">
          <Hexagon className="h-6 w-6 text-white dark:text-slate-900 fill-white/10 dark:fill-slate-900/10" strokeWidth={2} />
        </div>
        <span className="text-2xl font-black text-slate-900 dark:text-white tracking-tighter">PariLink</span>
      </div>

      <h2 className="text-3xl font-semibold tracking-tight text-slate-900 dark:text-white">
        Log in to your account
      </h2>
      <p className="mt-2 text-sm text-slate-500 dark:text-slate-400 font-medium">
        Securely access your enterprise workspace.
      </p>

      <div className="mt-8 relative">
        {isMfaRequired ? (
          <div className="space-y-6 animate-in slide-in-from-right-4 duration-300">
            <p className="text-sm text-slate-600 dark:text-slate-400">
              Please enter the 6-digit verification code generated by your Authenticator app.
            </p>
            {error && (
              <div className="p-3 text-sm text-red-700 bg-red-50 border border-red-200 rounded-lg animate-shake flex items-center gap-2 dark:bg-red-950/50 dark:border-red-900/50 dark:text-red-400">
                <AlertTriangle className="h-4 w-4" />
                {error}
              </div>
            )}
            <div className="space-y-2">
              <Label htmlFor="mfa" className="font-semibold">Verification Code</Label>
              <Input
                id="mfa"
                type="text"
                placeholder="000000"
                maxLength={6}
                className="text-2xl tracking-[0.5em] text-center font-mono h-14"
                onChange={(e) => {
                  if (e.target.value.length === 6) {
                    handleMfaSubmit(e.target.value);
                  }
                }}
              />
            </div>
            <Button className="w-full h-11" variant="outline" disabled={isLoading} onClick={() => setMfaRequired(false)}>
              Back to Login
            </Button>
          </div>
        ) : (
          <form onSubmit={handleSubmit(onSubmit)} className="space-y-5">
          {error && (
            <div className="p-3 text-sm text-red-700 bg-red-50 border border-red-200 rounded-lg animate-shake flex items-center gap-2 dark:bg-red-950/50 dark:border-red-900/50 dark:text-red-400">
              <AlertTriangle className="h-4 w-4" />
              {error}
            </div>
          )}

          <div className="space-y-1.5">
            <Label htmlFor="email" className="font-medium text-slate-700 dark:text-slate-300">Work Email</Label>
            <Input
              id="email"
              type="email"
              autoComplete="email"
              placeholder="name@company.com"
              {...register('email')}
              className={`h-11 transition-all duration-200 bg-white/50 dark:bg-slate-900/50 backdrop-blur-sm ${errors.email ? 'border-red-500 focus-visible:ring-red-500' : 'focus-visible:ring-slate-400 dark:focus-visible:ring-slate-600 hover:border-slate-400 dark:hover:border-slate-500'}`}
            />
            {errors.email && <p className="text-sm text-red-500 font-medium animate-in slide-in-from-top-1">{errors.email.message}</p>}
          </div>

          <div className="space-y-1.5">
            <div className="flex items-center justify-between">
              <Label htmlFor="password" className="font-medium text-slate-700 dark:text-slate-300">Password</Label>
              <a href="/forgot-password" className="text-sm font-semibold text-slate-900 hover:text-slate-700 dark:text-white dark:hover:text-slate-300 transition-colors">
                Forgot your password?
              </a>
            </div>
            <div className="relative">
              <Input
                id="password"
                type={showPassword ? "text" : "password"}
                autoComplete="current-password"
                {...register('password')}
                className={`h-11 pr-10 transition-all duration-200 bg-white/50 dark:bg-slate-900/50 backdrop-blur-sm ${errors.password ? 'border-red-500 focus-visible:ring-red-500' : 'focus-visible:ring-slate-400 dark:focus-visible:ring-slate-600 hover:border-slate-400 dark:hover:border-slate-500'}`}
              />
              <button
                type="button"
                onClick={() => setShowPassword(!showPassword)}
                className="absolute right-3 top-3 text-slate-400 hover:text-slate-600 dark:hover:text-slate-300 transition-colors"
                tabIndex={-1}
              >
                {showPassword ? <EyeOff className="h-5 w-5" /> : <Eye className="h-5 w-5" />}
              </button>
            </div>
            {capsLockOn && <p className="text-xs text-amber-600 dark:text-amber-400 font-medium flex items-center gap-1 mt-1"><AlertTriangle className="h-3 w-3" /> Caps Lock is on</p>}
            {errors.password && <p className="text-sm text-red-500 font-medium animate-in slide-in-from-top-1">{errors.password.message}</p>}
          </div>

          <div className="flex items-center space-x-2 pt-1 pb-2">
            <input type="checkbox" id="remember" className="rounded border-slate-300 text-slate-900 focus:ring-slate-900 dark:border-slate-700 dark:bg-slate-900 dark:checked:bg-white dark:focus:ring-white h-4 w-4 transition-all" />
            <Label htmlFor="remember" className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
              Remember this device for 30 days
            </Label>
          </div>

          <Button type="submit" className="w-full h-11 text-base font-semibold shadow-sm transition-all duration-200 hover:shadow-md bg-slate-900 text-white hover:bg-slate-800 dark:bg-white dark:text-slate-900 dark:hover:bg-slate-200" disabled={isLoading}>
            {isLoading ? (
              <span className="flex items-center gap-2">
                <Loader2 className="h-4 w-4 animate-spin" />
                Authenticating...
              </span>
            ) : (
              'Sign in to PariLink'
            )}
          </Button>
        </form>
        )}

        {!isMfaRequired && (
          <div className="mt-8">
            <div className="relative">
              <div className="absolute inset-0 flex items-center">
                <div className="w-full border-t border-slate-200 dark:border-slate-800" />
              </div>
              <div className="relative flex justify-center text-xs">
                <span className="bg-slate-50 dark:bg-slate-950 px-3 text-slate-500 uppercase font-semibold tracking-wider">Enterprise SSO</span>
              </div>
            </div>

            <div className="mt-6">
              <Button
                type="button"
                variant="outline"
                className="w-full h-11 font-medium bg-white/50 dark:bg-slate-900/50 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
                onClick={() => window.location.href = `${process.env.NEXT_PUBLIC_API_URL}/auth/saml/login`}
              >
                Continue with SAML SSO
              </Button>
            </div>
          </div>
        )}
      </div>

      <div className="mt-auto pt-10 text-center">
        <p className="text-xs text-slate-500 dark:text-slate-500 font-medium">
          © {new Date().getFullYear()} PariLink Enterprise. All rights reserved. V2.4.1
        </p>
        <div className="flex justify-center gap-4 mt-2 text-xs text-slate-500 dark:text-slate-500 font-medium">
          <a href="/legal/privacy" className="hover:text-slate-800 dark:hover:text-slate-300">Privacy Policy</a>
          <a href="/legal/terms" className="hover:text-slate-800 dark:hover:text-slate-300">Terms of Service</a>
        </div>
      </div>
    </div>
  );
}
