apiVersion: v1
kind: Service
metadata:
  name: parilink-api-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: parilink-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
